version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    container_name: campaign-backend
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/campaign-db
      - NODE_ENV=development
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: campaign-db

volumes:
  mongo_data:
